### ISSUE TITLE
源码库编译

### ISSUE THREAD

**Issue by Hikkovo** [LACHENNG/WeMeet#2]
您好，请问我需要如何编译源码库，可以出个教程吗

**Comment by Hikkovo** [comment]
例如protobuf，portaudio等第三方模块，我下载它们的源码后该如何编译

**Comment by LACHENNG** [comment]
你好，后续会在README中更新编译运行方法，此外，对应的第三方库（windows平台）已打包，可以先从网盘下载，放到非中文目录，然后修改CMakeList.txt指向对应的库路径。

链接：https://pan.baidu.com/s/1k6Wsdih2iUWMjMbvSERE6w?pwd=m07j 
提取码：m07j

**Comment by Hikkovo** [comment]
非常感谢
